import type { PartnersAccessLevel } from "@/lib/auth";

export type ToolClassification = "read" | "draft" | "guarded_write" | "restricted";

export type ToolDefinition = {
  name: string;
  description: string;
  classification: ToolClassification;
  accessLevel: PartnersAccessLevel;
  requiredPermissions: string[];
  requiresPropertyContext: boolean;
  requiresApproval: boolean;
  inputSummary: string;
  outputSummary: string;
};

export const TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    name: "get_dashboard_summary",
    description: "Get the Partners dashboard summary for the active property.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{}",
    outputSummary: "Dashboard summary object",
  },
  {
    name: "get_partner_account",
    description: "Get one partner account and its contacts, touches, and tasks.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string }",
    outputSummary: "Partner organization detail object",
  },
  {
    name: "get_partner_organization",
    description: "Legacy alias for get_partner_account.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string }",
    outputSummary: "Partner organization detail object",
  },
  {
    name: "find_partner_accounts",
    description: "List partner accounts filtered by query, stage, visit state, and saved view.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ query?: string, status?: string, visitStatus?: string, view?: string }",
    outputSummary: "Partner organization list",
  },
  {
    name: "find_partner_organizations",
    description: "Legacy alias for find_partner_accounts.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ query?: string, status?: string, visitStatus?: string, view?: string }",
    outputSummary: "Partner organization list",
  },
  {
    name: "list_not_contacted_partners",
    description: "List partner organizations that have not been contacted yet.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{}",
    outputSummary: "Partner organization list",
  },
  {
    name: "list_recent_active_accounts",
    description: "List the most recently active partner accounts for the active property.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ take?: number }",
    outputSummary: "Recently active account list",
  },
  {
    name: "list_saved_view_counts",
    description: "Get the counts for the main saved account views.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.organizations.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{}",
    outputSummary: "Saved-view counts",
  },
  {
    name: "list_tasks",
    description: "List tasks for the active property.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.tasks.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ bucket?: 'all' | 'overdue' | 'this_week' | 'mine', assignee?: string }",
    outputSummary: "Task list",
  },
  {
    name: "list_followups_due",
    description: "Legacy alias for list_tasks.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.tasks.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ bucket?: 'all' | 'overdue' | 'this_week' | 'mine', assignee?: string }",
    outputSummary: "Task list",
  },
  {
    name: "list_research_findings",
    description: "List raw partner research findings for review.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.research.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ status?: string, sourceType?: string, query?: string }",
    outputSummary: "Research finding list",
  },
  {
    name: "get_research_finding",
    description: "Get one research finding by id.",
    classification: "read",
    accessLevel: "read",
    requiredPermissions: ["partners.research.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ findingId: string }",
    outputSummary: "Research finding detail",
  },
  {
    name: "draft_intro_email",
    description: "Draft an introductory outreach email for a partner organization.",
    classification: "draft",
    accessLevel: "read",
    requiredPermissions: ["partners.outreach.read"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string }",
    outputSummary: "{ subject: string, body: string }",
  },
  {
    name: "create_partner_account",
    description: "Create a new partner account.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.organizations.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ name: string, type?: string, country?: string, city?: string, email?: string, phone?: string, whatsapp?: string, website?: string, source?: string, marketNotes?: string, nextActionAt?: string }",
    outputSummary: "Created account",
  },
  {
    name: "update_partner_profile",
    description: "Update partner profile and ownership fields.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.organizations.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string, country?: string, city?: string, email?: string, phone?: string, whatsapp?: string, website?: string, source?: string, marketNotes?: string, nextActionAt?: string, ownerUserId?: string, ownerUserName?: string, priority?: number }",
    outputSummary: "Updated account",
  },
  {
    name: "update_partner_status",
    description: "Update relationship status and visit status for a partner account.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.organizations.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string, status: string, visitStatus: string, visitNotes?: string }",
    outputSummary: "Updated account status",
  },
  {
    name: "add_partner_contact",
    description: "Add a contact to a partner account.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.contacts.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string, fullName: string, roleTitle?: string, email?: string, phone?: string, whatsapp?: string, preferredChannel?: string, notes?: string, isPrimary?: boolean }",
    outputSummary: "Created contact",
  },
  {
    name: "log_outreach_touch",
    description: "Log an outreach touch against a partner account.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.outreach.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string, contactId?: string, channel: string, happenedAt?: string, subject?: string, summary: string, outcome?: string, nextStep?: string, status?: string }",
    outputSummary: "Created outreach touch",
  },
  {
    name: "create_task",
    description: "Create a task for a partner account.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.tasks.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string, contactId?: string, title: string, description?: string, dueAt: string, assignedToUserId?: string, assignedToUserName?: string }",
    outputSummary: "Created task",
  },
  {
    name: "assign_task",
    description: "Assign a task to a user.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.tasks.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ taskId: string, assignedToUserId?: string, assignedToUserName?: string }",
    outputSummary: "Updated task",
  },
  {
    name: "complete_task",
    description: "Mark a task as done.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.tasks.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ taskId: string }",
    outputSummary: "Completed task",
  },
  {
    name: "reopen_task",
    description: "Reopen a completed task.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.tasks.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ taskId: string }",
    outputSummary: "Reopened task",
  },
  {
    name: "create_research_finding",
    description: "Create a raw research finding without directly mutating partner accounts.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.research.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ sourceType?: string, sourceUrl?: string, sourceHandle?: string, observedName?: string, observedText?: string, extractedDataJson?: object, confidence?: number, proposedOrganizationId?: string }",
    outputSummary: "Created research finding",
  },
  {
    name: "review_research_finding",
    description: "Mark a research finding as reviewed.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.research.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ findingId: string }",
    outputSummary: "Updated research finding",
  },
  {
    name: "discard_research_finding",
    description: "Discard a research finding.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.research.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ findingId: string }",
    outputSummary: "Updated research finding",
  },
  {
    name: "promote_research_finding",
    description: "Promote a research finding into a partner account.",
    classification: "guarded_write",
    accessLevel: "write",
    requiredPermissions: ["partners.research.write"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ findingId: string }",
    outputSummary: "Promoted organization or finding",
  },
  {
    name: "send_intro_email",
    description: "Send the intro email to a partner account using Resend.",
    classification: "restricted",
    accessLevel: "admin",
    requiredPermissions: ["partners.outreach.send"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string, contactId?: string, recipientEmail: string, recipientLabel?: string, subject: string, body: string }",
    outputSummary: "{ messageId: string, touchId: string }",
  },
  {
    name: "archive_partner_account",
    description: "Archive a partner account.",
    classification: "restricted",
    accessLevel: "admin",
    requiredPermissions: ["partners.admin"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string }",
    outputSummary: "Archived account",
  },
  {
    name: "unarchive_partner_account",
    description: "Unarchive a partner account.",
    classification: "restricted",
    accessLevel: "admin",
    requiredPermissions: ["partners.admin"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationId: string }",
    outputSummary: "Unarchived account",
  },
  {
    name: "bulk_update_accounts",
    description: "Run a bulk update across multiple partner accounts.",
    classification: "restricted",
    accessLevel: "admin",
    requiredPermissions: ["partners.admin"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationIds: string[], action: 'mark_contacted' | 'mark_awaiting_reply' | 'assign_to_me' }",
    outputSummary: "Bulk update result",
  },
  {
    name: "bulk_schedule_tasks",
    description: "Create the same task across multiple partner accounts.",
    classification: "restricted",
    accessLevel: "admin",
    requiredPermissions: ["partners.admin"],
    requiresPropertyContext: true,
    requiresApproval: false,
    inputSummary: "{ organizationIds: string[], title: string, description?: string, dueAt: string }",
    outputSummary: "Bulk schedule result",
  },
];
